/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package controlclientes;

import java.awt.Dialog.ModalityType;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author vgtx
 */
public class Principal extends javax.swing.JFrame {

    private final DB database = new DB();
    private String nombreCliente;
    private String apellidoCliente;
    private String fechaNacimientoCliente;
    private String telefonoCliente;
    private String codigoCliente;
    
    public Principal() throws ClassNotFoundException {
        initComponents();

        tablaClientes.setModel(database.getClientes());
        this.setLocationRelativeTo(null);
        ImageIcon favicon = new ImageIcon(getClass().getResource("/img/iconoTijeras.png"));
        this.setIconImage(favicon.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ventanaAgregarCliente = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        campoApellido = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        campoFechaNacimiento = new com.toedter.calendar.JDateChooser();
        campoTelefono = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        btnCargarCliente = new javax.swing.JButton();
        ventanaAgregarCorte = new javax.swing.JDialog();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        campoFechaCorte = new com.toedter.calendar.JDateChooser();
        campoCliente = new javax.swing.JTextField();
        btnCargarCorte = new javax.swing.JButton();
        campoBusqueda = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaClientes = new javax.swing.JTable();
        btnBuscar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaCortes = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnAgregarCorte = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnEliminarCorte = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnAgregarCliente = new javax.swing.JButton();
        btnEditarCliente = new javax.swing.JButton();
        btnEliminarCliente = new javax.swing.JButton();
        btnEditarCorte = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        campoClienteCorte = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        ventanaAgregarCliente.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        ventanaAgregarCliente.setTitle("Agregar Cliente");
        ventanaAgregarCliente.setResizable(false);

        jLabel8.setBackground(new java.awt.Color(51, 51, 51));
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("NUEVO CLIENTE");
        jLabel8.setOpaque(true);

        jLabel9.setText("Nombre");

        jLabel10.setText("Apellido");

        jLabel11.setText("Fecha de Nacimiento");

        jLabel12.setText("Numero de Telefono");

        btnCargarCliente.setBackground(new java.awt.Color(51, 51, 51));
        btnCargarCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnCargarCliente.setText("CARGAR");
        btnCargarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCargarCliente)
                        .addGap(253, 253, 253))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(campoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(campoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(84, 84, 84))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCargarCliente)
                .addContainerGap())
        );

        javax.swing.GroupLayout ventanaAgregarClienteLayout = new javax.swing.GroupLayout(ventanaAgregarCliente.getContentPane());
        ventanaAgregarCliente.getContentPane().setLayout(ventanaAgregarClienteLayout);
        ventanaAgregarClienteLayout.setHorizontalGroup(
            ventanaAgregarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 583, Short.MAX_VALUE)
            .addGroup(ventanaAgregarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ventanaAgregarClienteLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        ventanaAgregarClienteLayout.setVerticalGroup(
            ventanaAgregarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 229, Short.MAX_VALUE)
            .addGroup(ventanaAgregarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ventanaAgregarClienteLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        ventanaAgregarCorte.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        ventanaAgregarCorte.setTitle("Agregar Cliente");
        ventanaAgregarCorte.setResizable(false);

        jLabel13.setBackground(new java.awt.Color(51, 51, 51));
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("AGREGAR CORTE");
        jLabel13.setOpaque(true);

        jLabel16.setText("Fecha del corte");

        jLabel17.setText("Cliente");

        campoCliente.setEnabled(false);

        btnCargarCorte.setBackground(new java.awt.Color(51, 51, 51));
        btnCargarCorte.setForeground(new java.awt.Color(255, 255, 255));
        btnCargarCorte.setText("CARGAR");
        btnCargarCorte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarCorteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ventanaAgregarCorteLayout = new javax.swing.GroupLayout(ventanaAgregarCorte.getContentPane());
        ventanaAgregarCorte.getContentPane().setLayout(ventanaAgregarCorteLayout);
        ventanaAgregarCorteLayout.setHorizontalGroup(
            ventanaAgregarCorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
            .addGroup(ventanaAgregarCorteLayout.createSequentialGroup()
                .addGroup(ventanaAgregarCorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ventanaAgregarCorteLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(ventanaAgregarCorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoFechaCorte, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ventanaAgregarCorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(campoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ventanaAgregarCorteLayout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addComponent(btnCargarCorte)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ventanaAgregarCorteLayout.setVerticalGroup(
            ventanaAgregarCorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventanaAgregarCorteLayout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(ventanaAgregarCorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ventanaAgregarCorteLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(ventanaAgregarCorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(campoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ventanaAgregarCorteLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(campoFechaCorte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(btnCargarCorte)
                .addGap(32, 32, 32))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nando | Gestion de Clientes");

        campoBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoBusquedaKeyPressed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Buscar por campo");

        tablaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Jorgito", "Perez", "19/09/2001", "3815679402"}
            },
            new String [] {
                "Nombre", "Apellido", "Fec. Nac.", "Nro. Tel."
            }
        ));
        tablaClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaClientes);

        btnBuscar.setBackground(new java.awt.Color(51, 51, 51));
        btnBuscar.setForeground(new java.awt.Color(204, 204, 204));
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        tablaCortes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha"
            }
        ));
        jScrollPane2.setViewportView(tablaCortes);

        jLabel2.setBackground(new java.awt.Color(51, 51, 51));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CORTES");
        jLabel2.setOpaque(true);

        btnAgregarCorte.setBackground(new java.awt.Color(51, 51, 51));
        btnAgregarCorte.setForeground(new java.awt.Color(204, 204, 204));
        btnAgregarCorte.setText("Agregar");
        btnAgregarCorte.setEnabled(false);
        btnAgregarCorte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCorteActionPerformed(evt);
            }
        });

        jLabel3.setText("Gestion de cortes");

        btnEliminarCorte.setBackground(new java.awt.Color(51, 51, 51));
        btnEliminarCorte.setForeground(new java.awt.Color(204, 204, 204));
        btnEliminarCorte.setText("Eliminar");
        btnEliminarCorte.setEnabled(false);
        btnEliminarCorte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarCorteActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(51, 51, 51));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("CLIENTES");
        jLabel4.setOpaque(true);

        btnAgregarCliente.setBackground(new java.awt.Color(51, 51, 51));
        btnAgregarCliente.setForeground(new java.awt.Color(204, 204, 204));
        btnAgregarCliente.setText("Agregar");
        btnAgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarClienteActionPerformed(evt);
            }
        });

        btnEditarCliente.setBackground(new java.awt.Color(51, 51, 51));
        btnEditarCliente.setForeground(new java.awt.Color(204, 204, 204));
        btnEditarCliente.setText("Editar");
        btnEditarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarClienteActionPerformed(evt);
            }
        });

        btnEliminarCliente.setBackground(new java.awt.Color(51, 51, 51));
        btnEliminarCliente.setForeground(new java.awt.Color(204, 204, 204));
        btnEliminarCliente.setText("Eliminar");
        btnEliminarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarClienteActionPerformed(evt);
            }
        });

        btnEditarCorte.setBackground(new java.awt.Color(51, 51, 51));
        btnEditarCorte.setForeground(new java.awt.Color(204, 204, 204));
        btnEditarCorte.setText("Editar");
        btnEditarCorte.setEnabled(false);
        btnEditarCorte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarCorteActionPerformed(evt);
            }
        });

        jLabel5.setText("Gestión de cliente");

        campoClienteCorte.setEnabled(false);

        jLabel6.setText("Cortes del cliente");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(campoClienteCorte, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAgregarCorte)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEditarCorte)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEliminarCorte))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(campoBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscar))
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAgregarCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEditarCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEliminarCliente)))))
                .addContainerGap())
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar)
                    .addComponent(btnAgregarCliente)
                    .addComponent(btnEditarCliente)
                    .addComponent(btnEliminarCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoClienteCorte, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAgregarCorte)
                        .addComponent(btnEliminarCorte)
                        .addComponent(btnEditarCorte)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarClienteActionPerformed
        ventanaAgregarCliente.setModalityType(ModalityType.APPLICATION_MODAL);
        ventanaAgregarCliente.pack();
        ventanaAgregarCliente.setLocationRelativeTo(null);
        ventanaAgregarCliente.setVisible(true);
    }//GEN-LAST:event_btnAgregarClienteActionPerformed

    private void tablaClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaClientesMouseClicked
        if (tablaClientes.getSelectedRow() != -1) {
            int row = tablaClientes.getSelectedRow();
            codigoCliente = tablaClientes.getValueAt(row, 0).toString();
            nombreCliente = tablaClientes.getValueAt(row, 1).toString();
            apellidoCliente = tablaClientes.getValueAt(row, 2).toString();
            fechaNacimientoCliente = tablaClientes.getValueAt(row, 3).toString();
            telefonoCliente = tablaClientes.getValueAt(row, 4).toString();
            campoCliente.setText(nombreCliente + " " + apellidoCliente);
            campoClienteCorte.setText(nombreCliente + " " + apellidoCliente);
            tablaCortes.setModel(database.getCortes(codigoCliente));
            btnAgregarCorte.setEnabled(true);
            btnEditarCorte.setEnabled(true);
            btnEliminarCorte.setEnabled(true);
        }
    }//GEN-LAST:event_tablaClientesMouseClicked

    private void btnCargarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarClienteActionPerformed
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String nombre = campoNombre.getText();
        String apellido = campoApellido.getText();
        String fecha_nacimiento = "";
        String telefono = campoTelefono.getText();
        try {
            fecha_nacimiento = sdf.format(campoFechaNacimiento.getDate());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Formato de fecha incorrecto.", "Error!", 1);
        }

        try {
            campoNombre.setText("");
            campoApellido.setText("");
            campoTelefono.setText("");
            database.addCliente(nombre, apellido, fecha_nacimiento, telefono);
            tablaClientes.setModel(database.getClientes());
            ventanaAgregarCliente.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Revisa los campos e intenta nuevamente.", "Error!", 1);
        }
    }//GEN-LAST:event_btnCargarClienteActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String busqueda = campoBusqueda.getText();

        if (busqueda.length() > 0) {
            tablaClientes.setModel(database.getClientes(busqueda));
        } else {
            tablaClientes.setModel(database.getClientes());
        }

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEditarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarClienteActionPerformed
        if (tablaClientes.getSelectedRow() != -1) {
            int row = tablaClientes.getSelectedRow();
            String nombre = tablaClientes.getValueAt(row, 1).toString();
            String apellido = tablaClientes.getValueAt(row, 2).toString();
            String fecha = tablaClientes.getValueAt(row, 3).toString();
            String telefono = tablaClientes.getValueAt(row, 4).toString();

            database.editCliente(nombre, apellido, fecha, telefono, codigoCliente);
            JOptionPane.showMessageDialog(null, "Se edito correctamente el cliente! <Recuerde que no se puede editar el codigo>", "Exito!", 1);
            tablaClientes.setModel(database.getClientes());
        } else {
            JOptionPane.showMessageDialog(null, "Selecciona un cliente de la lista primero!", "Error!", 1);
        }
    }//GEN-LAST:event_btnEditarClienteActionPerformed

    private void btnEliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarClienteActionPerformed
        if (tablaClientes.getSelectedRow() != -1) {
            int opc = JOptionPane.showConfirmDialog(null, "¿Esta seguro de eliminar el cliente " + nombreCliente + "?", "Eliminar Cliente", JOptionPane.YES_NO_OPTION);

            if (opc == JOptionPane.YES_OPTION) {
                database.deleteCliente(codigoCliente);
                tablaClientes.setModel(database.getClientes());
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecciona un cliente de la lista primero!", "Error!", 1);
        }
    }//GEN-LAST:event_btnEliminarClienteActionPerformed

    private void campoBusquedaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoBusquedaKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            btnBuscarActionPerformed(null);
        }
    }//GEN-LAST:event_campoBusquedaKeyPressed

    private void btnCargarCorteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarCorteActionPerformed
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String fechaCorte = "";
        try {
            fechaCorte = sdf.format(campoFechaCorte.getDate());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Formato de fecha incorrecto.", "Error!", 1);
        }
        
        try {
            database.addCorte(codigoCliente, fechaCorte);
            tablaCortes.setModel(database.getCortes(codigoCliente));
            ventanaAgregarCorte.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Revisa los campos e intenta nuevamente.", "Error!", 1);
        }
    }//GEN-LAST:event_btnCargarCorteActionPerformed

    private void btnAgregarCorteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCorteActionPerformed
        ventanaAgregarCorte.setModalityType(ModalityType.APPLICATION_MODAL);
        ventanaAgregarCorte.pack();
        ventanaAgregarCorte.setLocationRelativeTo(null);
        ventanaAgregarCorte.setVisible(true);
        tablaCortes.setModel(database.getCortes(codigoCliente));
    }//GEN-LAST:event_btnAgregarCorteActionPerformed

    private void btnEditarCorteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarCorteActionPerformed
        if(tablaCortes.getSelectedRow() != -1){
            int row = tablaCortes.getSelectedRow();
            String codigo = tablaCortes.getValueAt(row, 0).toString();
            String fecha = tablaCortes.getValueAt(row, 1).toString();
            database.editCorte(codigoCliente, fecha, codigo);
            JOptionPane.showMessageDialog(null, "Se edito correctamente el corte! <Recuerde que no se puede editar el codigo>", "Error!", 1);
            tablaCortes.setModel(database.getCortes(codigoCliente));
        }else {
            JOptionPane.showMessageDialog(null, "Selecciona un corte de la lista primero!", "Error!", 1);
        }
    }//GEN-LAST:event_btnEditarCorteActionPerformed

    private void btnEliminarCorteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarCorteActionPerformed
        if (tablaCortes.getSelectedRow() != -1) {
            int opc = JOptionPane.showConfirmDialog(null, "¿Esta seguro de eliminar el corte seleccionado?", "Eliminar Corte", JOptionPane.YES_NO_OPTION);

            if (opc == JOptionPane.YES_OPTION) {
                int row = tablaCortes.getSelectedRow();
                String codigo = tablaCortes.getValueAt(row, 0).toString();
                database.deleteCorte(codigoCliente, codigo);
                tablaCortes.setModel(database.getCortes(codigoCliente));
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecciona un cliente de la lista primero!", "Error!", 1);
        }
    }//GEN-LAST:event_btnEliminarCorteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Principal().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarCliente;
    private javax.swing.JButton btnAgregarCorte;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCargarCliente;
    private javax.swing.JButton btnCargarCorte;
    private javax.swing.JButton btnEditarCliente;
    private javax.swing.JButton btnEditarCorte;
    private javax.swing.JButton btnEliminarCliente;
    private javax.swing.JButton btnEliminarCorte;
    private javax.swing.JTextField campoApellido;
    private javax.swing.JTextField campoBusqueda;
    private javax.swing.JTextField campoCliente;
    private javax.swing.JTextField campoClienteCorte;
    private com.toedter.calendar.JDateChooser campoFechaCorte;
    private com.toedter.calendar.JDateChooser campoFechaNacimiento;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JTextField campoTelefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaClientes;
    private javax.swing.JTable tablaCortes;
    private javax.swing.JDialog ventanaAgregarCliente;
    private javax.swing.JDialog ventanaAgregarCorte;
    // End of variables declaration//GEN-END:variables
}
